In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import knn as knn

In [3]:
import os
import pandas as pd
import numpy as np
from scipy import stats
import heapq
import random

In [4]:
k = knn.KNN()

In [5]:
k.loadData('pa1train.txt')

In [15]:
k.predict(k.model[9],7)

0

In [58]:
kth_nearest = pd.DataFrame({"distance":distance, "labels":k.labels}).sort_values("distance")[:5]

In [68]:
stats.mode(k.labels)

ModeResult(mode=array([0]), count=array([200]))

In [69]:
np.unique(k.labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
k.labels == 0

array([ True,  True,  True, ..., False, False, False])

In [35]:
# heapq.heapfy(k.label)
random_arr = [random.randint(0,9) for i in range(30)]
counts = [np.sum(random_arr == unique) for unique in np.unique(random_arr)]

In [26]:
np.unique(random_arr)[counts == np.amax(counts)]

array([4, 7])

In [41]:
knn.find_mode(random_arr)

3